import React, { useState } from 'react';
import { 
  History, 
  Plus, 
  Download, 
  Trash2, 
  Clock, 
  FileText
} from 'lucide-react';
import type { PortCall, SOFEvent } from '../types';

interface SOFProps {
  portCall: PortCall;
  onAddSOFEvent: (
    portCallId: string, 
    description: string, 
    category: SOFEvent['category'], 
    laytimeImpact: SOFEvent['laytimeImpact'], 
    loggedBy: string
  ) => void;
  onDeleteSOFEvent: (portCallId: string, eventId: string) => void;
}

const StatementOfFacts: React.FC<SOFProps> = ({ portCall, onAddSOFEvent, onDeleteSOFEvent }) => {
  const [filter, setFilter] = useState<string>('All');
  const [desc, setDesc] = useState<string>('');
  const [category, setCategory] = useState<SOFEvent['category']>('Cargo');
  const [impact, setImpact] = useState<SOFEvent['laytimeImpact']>('Full');
  const [operatorName, setOperatorName] = useState<string>('Port Agent Sarah');

  // Filter events
  const filteredEvents = portCall.sofEvents.filter(e => {
    if (filter === 'All') return true;
    if (filter === 'Delays') return e.category === 'Delay';
    return e.category.toLowerCase() === filter.toLowerCase();
  });

  // Preset quick logs to make data logging frictionless
  const quickLogPresets = [
    { label: 'NOR Tendered', desc: 'Notice of Readiness (NOR) tendered', cat: 'Administrative' as const, imp: 'Excluded' as const },
    { label: 'Pilot Onboard', desc: 'Pilot onboard for harbor entry', cat: 'Navigation' as const, imp: 'Excluded' as const },
    { label: 'All Fast', desc: 'Vessel all fast at berth', cat: 'Navigation' as const, imp: 'Excluded' as const },
    { label: 'Loading Commenced', desc: 'Cargo loading operations commenced', cat: 'Cargo' as const, imp: 'Full' as const },
    { label: 'Rain Delay', desc: 'Precipitation/Rain delay - Cargo operations halted', cat: 'Delay' as const, imp: 'Excluded' as const },
    { label: 'Delay Resumed', desc: 'Rain cleared - Cargo operations resumed', cat: 'Cargo' as const, imp: 'Full' as const },
    { label: 'Ops Completed', desc: 'Cargo loading operations completed', cat: 'Cargo' as const, imp: 'Full' as const }
  ];

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!desc.trim()) return;
    onAddSOFEvent(portCall.id, desc, category, impact, operatorName);
    setDesc('');
  };

  const handleQuickLog = (preset: typeof quickLogPresets[0]) => {
    onAddSOFEvent(portCall.id, preset.desc, preset.cat, preset.imp, operatorName);
  };

  // CSV Exporter
  const exportToCSV = () => {
    const headers = 'ID,Timestamp UTC,Event Description,Category,Laytime Impact,Logged By\n';
    const rows = portCall.sofEvents.map(e => {
      const escapedDesc = e.description.replace(/"/g, '""');
      return `"${e.id}","${e.timestamp}","${escapedDesc}","${e.category}","${e.laytimeImpact}","${e.loggedBy}"`;
    }).join('\n');

    const blob = new Blob([headers + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `SOF_${portCall.vessel.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Text Report Exporter
  const exportToTXT = () => {
    let report = `==================================================\n`;
    report += `          STATEMENT OF FACTS REPORT (SOF)        \n`;
    report += `==================================================\n\n`;
    report += `Vessel Name : ${portCall.vessel.name}\n`;
    report += `IMO Number  : ${portCall.vessel.imo}\n`;
    report += `Flag        : ${portCall.vessel.flag}\n`;
    report += `Type        : ${portCall.vessel.type}\n`;
    report += `Cargo       : ${portCall.cargoQty.toLocaleString()} Tons ${portCall.cargoType}\n`;
    report += `Port Agent  : ${portCall.agentName}\n\n`;
    report += `CHRONOLOGICAL LOG OF EVENTS:\n`;
    report += `--------------------------------------------------\n`;
    
    portCall.sofEvents.forEach(e => {
      const time = new Date(e.timestamp).toUTCString().replace('GMT', 'UTC');
      report += `[${time}] [${e.category.toUpperCase()}] (${e.laytimeImpact} Laytime)\n`;
      report += `-> ${e.description} (Logged by: ${e.loggedBy})\n\n`;
    });

    report += `==================================================\n`;
    report += `Generated by DockFlow Operations Portal on ${new Date().toISOString()}\n`;

    const blob = new Blob([report], { type: 'text/plain;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', `SOF_Report_${portCall.vessel.name.replace(/\s+/g, '_')}.txt`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="sof-layout">
      {/* Left Column: Form & Presets */}
      <section className="glass-panel sof-logger-form">
        <h3 style={{ fontFamily: 'var(--font-display)', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <History size={18} className="teal-glow" />
          Log Statement Event
        </h3>

        <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          <div className="form-group">
            <label htmlFor="agent-name">Logged By (Agent/VTS)</label>
            <input 
              id="agent-name"
              type="text" 
              className="form-control"
              value={operatorName}
              onChange={(e) => setOperatorName(e.target.value)}
              required
            />
          </div>

          <div className="form-group">
            <label htmlFor="event-desc">Event Description</label>
            <input 
              id="event-desc"
              type="text" 
              className="form-control"
              placeholder="e.g. Tugboat secured starboard side, crane breakdown..."
              value={desc}
              onChange={(e) => setDesc(e.target.value)}
              required
            />
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
            <div className="form-group">
              <label htmlFor="event-cat">Category</label>
              <select 
                id="event-cat"
                className="form-control"
                value={category}
                onChange={(e) => setCategory(e.target.value as any)}
              >
                <option value="Navigation">Navigation</option>
                <option value="Cargo">Cargo Ops</option>
                <option value="Service">Services</option>
                <option value="Administrative">Admin</option>
                <option value="Delay">Delay Alert</option>
              </select>
            </div>

            <div className="form-group">
              <label htmlFor="event-impact">Laytime Impact</label>
              <select 
                id="event-impact"
                className="form-control"
                value={impact}
                onChange={(e) => setImpact(e.target.value as any)}
              >
                <option value="Full">100% Laytime</option>
                <option value="Half">50% Laytime</option>
                <option value="Excluded">0% (Excluded)</option>
              </select>
            </div>
          </div>

          <button 
            type="submit" 
            className="action-btn"
            style={{ marginTop: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px' }}
          >
            <Plus size={16} /> Log Fact Entry
          </button>
        </form>

        {/* Quick Log Presets */}
        <div style={{ marginTop: '24px', paddingTop: '20px', borderTop: '1px solid var(--card-border)' }}>
          <h4 style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '12px' }}>Quick Log Presets:</h4>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
            {quickLogPresets.map((preset, idx) => (
              <button 
                key={idx}
                className="filter-btn"
                style={{ fontSize: '0.75rem', padding: '4px 8px' }}
                onClick={() => handleQuickLog(preset)}
              >
                {preset.label}
              </button>
            ))}
          </div>
        </div>
      </section>

      {/* Right Column: Statement of Facts Log Timeline */}
      <section className="glass-panel sof-events-panel">
        <div className="table-header" style={{ marginBottom: '16px' }}>
          <div className="d-flex align-center gap-16">
            <h3 style={{ fontSize: '1.1rem', fontFamily: 'var(--font-display)' }}>Event Log Timeline</h3>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>({portCall.sofEvents.length} events logged)</span>
          </div>

          <div className="d-flex gap-8">
            <button 
              className="action-btn" 
              style={{ display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 10px', fontSize: '0.75rem' }}
              onClick={exportToCSV}
              disabled={portCall.sofEvents.length === 0}
            >
              <Download size={12} /> CSV
            </button>
            <button 
              className="action-btn" 
              style={{ display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 10px', fontSize: '0.75rem', borderColor: 'var(--blue-dim)', color: 'var(--blue-ocean)' }}
              onClick={exportToTXT}
              disabled={portCall.sofEvents.length === 0}
            >
              <FileText size={12} /> TXT Report
            </button>
          </div>
        </div>

        {/* Chronological Filter Bar */}
        <div className="table-filters" style={{ marginBottom: '16px' }}>
          {['All', 'Navigation', 'Cargo', 'Administrative', 'Delays'].map(f => (
            <button 
              key={f}
              className={`filter-btn ${filter === f ? 'active' : ''}`}
              style={{ fontSize: '0.75rem', padding: '4px 10px' }}
              onClick={() => setFilter(f)}
            >
              {f}
            </button>
          ))}
        </div>

        {/* Events Scroller */}
        <div className="sof-list">
          {filteredEvents.map(e => (
            <div 
              key={e.id} 
              className={`glass-panel sof-event-card ${e.category.toLowerCase()}`}
            >
              <div className="sof-event-main">
                <div className="sof-event-desc">{e.description}</div>
                <div className="sof-event-time">
                  <Clock size={10} style={{ display: 'inline', marginRight: '4px', verticalAlign: 'text-bottom' }} />
                  {new Date(e.timestamp).toUTCString().replace('GMT', 'UTC')}
                </div>
                <div style={{ display: 'flex', gap: '8px', marginTop: '6px' }}>
                  <span className="sof-event-badge">{e.category}</span>
                  <span className={`sof-event-impact-badge ${e.laytimeImpact.toLowerCase()}`}>
                    Impact: {e.laytimeImpact === 'Full' ? '100%' : e.laytimeImpact === 'Half' ? '50%' : 'Excluded'}
                  </span>
                  <span style={{ fontSize: '0.7rem', color: 'var(--text-dim)', alignSelf: 'center' }}>by {e.loggedBy}</span>
                </div>
              </div>

              <button 
                className="event-delete-btn"
                title="Delete Entry"
                onClick={() => onDeleteSOFEvent(portCall.id, e.id)}
              >
                <Trash2 size={14} />
              </button>
            </div>
          ))}

          {filteredEvents.length === 0 && (
            <div style={{ textAlign: 'center', padding: '48px 0', color: 'var(--text-dim)', fontSize: '0.9rem' }}>
              No statement events found matching filter.
            </div>
          )}
        </div>
      </section>
    </div>
  );
};

export default StatementOfFacts;
